app:
  github:
    token: ${GITHUB_TOKEN:}
    api-url: https://api.github.com
  webhook:
    secret: ${GITHUB_WEBHOOK_SECRET:}

spring:
  application:
    name: code-review-agent
  config:
    import: optional:file:.env[.properties]
  main:
    web-application-type: reactive
  shell:
    interactive:
      enabled: true

embabel:
  models:
    default-llm: gpt-4.1-nano   # Modelo más económico de OpenAI
  agent:
    platform:
      models:
        openai:
          max-attempts: 3
          backoff-millis: 2000
    logging:
      personality: starwars
      verbosity: info
    shell:
      web-application-type: reactive